### ISSUE TITLE
Can't use emoji

### ISSUE THREAD

**Issue by rezafaizarahman** [mailtarget/mailtarget-wp-plugin#2]
Ketika _setup new form_ di wordpress, kemudian pada title menggunakan emoji. Nanti formnya tidak muncul. 
![screen shot 2018-01-08 at 3 05 53 pm](https://user-images.githubusercontent.com/1758606/34662747-750cd00e-f485-11e7-8cc9-ed252ef377c8.png)

**Comment by timenz** [comment]
Its because this plugin using utf8 table charset, I'll update it to utf8mb4 soon.
but actually it's only affect on field 'name' the others is fine
